services:

  backend:
    build:
      context: ./backend
    container_name: ukko-beta-demo-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    restart: unless-stopped

  frontend:
    build:
      context: ./react-app
    container_name: ukko-beta-demo-ui
    ports:
      - "5173:5173"
    env_file:
      - ./react-app/.env
    depends_on:
      - backend
    restart: unless-stopped
